// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGpbx355jDAEODN8YWpq0tvh7toTF6gZs',
    appId: '1:595086610771:web:653436b6b7e51e934551a6',
    messagingSenderId: '595086610771',
    projectId: 'notifications-449cc',
    authDomain: 'notifications-449cc.firebaseapp.com',
    storageBucket: 'notifications-449cc.firebasestorage.app',
    measurementId: 'G-MK4C0BX16N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcv6TAzCGujjXgO_Sit5qWEo8ca6nKexM',
    appId: '1:595086610771:android:8d54095252b682d54551a6',
    messagingSenderId: '595086610771',
    projectId: 'notifications-449cc',
    storageBucket: 'notifications-449cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABx2t6UeOtQGiPHAks75y0YR8_roUZcwU',
    appId: '1:595086610771:ios:dda8dbdac7797c7f4551a6',
    messagingSenderId: '595086610771',
    projectId: 'notifications-449cc',
    storageBucket: 'notifications-449cc.firebasestorage.app',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABx2t6UeOtQGiPHAks75y0YR8_roUZcwU',
    appId: '1:595086610771:ios:dda8dbdac7797c7f4551a6',
    messagingSenderId: '595086610771',
    projectId: 'notifications-449cc',
    storageBucket: 'notifications-449cc.firebasestorage.app',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGpbx355jDAEODN8YWpq0tvh7toTF6gZs',
    appId: '1:595086610771:web:3af888292cbebc404551a6',
    messagingSenderId: '595086610771',
    projectId: 'notifications-449cc',
    authDomain: 'notifications-449cc.firebaseapp.com',
    storageBucket: 'notifications-449cc.firebasestorage.app',
    measurementId: 'G-F500D6CRCF',
  );
}
