import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:notifications/notifications/notifications_screen.dart';
import 'firebase_options.dart'; // auto-generated by flutterfire
import 'home_screen.dart';

// object to show notifications
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

// channel settings for notificaions
const AndroidNotificationChannel channel = AndroidNotificationChannel(
  'high_importance_channel', // معرف القناة
  'High Importance Notifications', // اسم القناة
  description: 'This channel is used for important notifications.', // وصف
  importance: Importance.high,
);

// showing messages in BackGround
Future<void> _firebaseMessagingBackGroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  print('Handling a background message: ${message.messageId}');
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  FirebaseMessaging messaging = FirebaseMessaging.instance;
  // channel creating
  await flutterLocalNotificationsPlugin
      .resolvePlatformSpecificImplementation<
        AndroidFlutterLocalNotificationsPlugin
      >()
      ?.createNotificationChannel(channel);
  // recive messages in BackGround
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackGroundHandler);
  // get device token
  FirebaseMessaging.instance.getToken().then((token) {
    print('FCM Token: $token');
  });
  NotificationSettings settings = await messaging.requestPermission(
    alert: true,
    badge: true,
    sound: true,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter + Firebase App',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const NotificationsScreen(),
    );
  }
}
